AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline
Parameters:
  ClientShortName:
    Description: Client Short Name
    Type: String
    Default: Web-portal
  ApplicationName:
    Description: Client Short Name
    Type: String
    Default: Test-CodePipeline
  GitHubUser:
    Description: The GitHub username which owns the repository to be deployed
    Type: String
    Default: Urvesh05
  GitHubRepository:
    Description: The name of the repository to deploy
    Type: String
    Default: testRepo
  GitHubBranch:
    Description: The branch of the repository to deploy
    Type: String
    Default: master
  GitOAuthToken:
    Description: oauth token
    Type: String
    Default: '******'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: ObjectWriter
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name:
        Fn::Join:
        - '-'
        - - test
          - Ref: CodePipelineName
      RoleArn:
        Ref: CodePipelineRole
      Tags:
      - Key: Name
        Value:
          Ref: CodePipelineName
      Stages:
      - Name: Source
        Actions:
        - Name: GitHub
          RunOrder: 1
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            Owner:
              Ref: GitHubUser
            Repo:
              Ref: GitHubRepository
            Branch:
              Ref: GitHubBranch
            OAuthToken:
              Ref: GitOAuthToken
      - Name: Build
        Actions:
        - Name: Build
          RunOrder: 1
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: 1
          Configuration:
            ApplicationName:
              Ref: CodeBuildProject
          InputArtifacts:
          - Name: SourceArtifact
          OutputArtifacts:
          - Name: Build Output
      ArtifactStore:
        Type: S3
        Location:
          Ref: S3Bucket
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-CodeBuild
      Description: CodePipeline serverless deployer.
      ServiceRole:
        Fn::GetAtt:
        - CodeBuildRole
        - Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Artifacts:
        Name:
          Fn::Join:
          - '-'
          - - test-deploy
            - Ref: ClientShortName
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: role-${ApplicationName}-${ClientShortName}web-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: codepipeline.amazonaws.com
      Policies:
      - PolicyName:
          Fn::Sub: policy-${ApplicationName}-${ClientShortName}web-${AWS::Region}
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: S3AccessPolicy
            Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: '*'
          - Sid: CodeBuildAccessPolicy
            Effect: Allow
            Action:
            - codedeploy:CreateDeployment
            - codedeploy:GetApplicationRevision
            - codedeploy:GetDeployment
            - codedeploy:GetDeploymentConfig
            - codedeploy:RegisterApplicationRevision
            - codebuild:BatchGetBuilds
            - codebuild:StartBuild
            Resource: '*'
          - Sid: cloudformationPolicy
            Effect: Allow
            Action:
            - cloudformation:CreateStack
            - cloudformation:DeleteStack
            - cloudformation:DescribeStacks
            - cloudformation:UpdateStack
            - cloudformation:CreateChangeSet
            - cloudformation:DeleteChangeSet
            - cloudformation:DescribeChangeSet
            - cloudformation:ExecuteChangeSet
            - cloudformation:SetStackPolicy
            - cloudformation:ValidateTemplate
            Resource: '*'
          - Effect: Allow
            Action:
            - iam:PassRole
            Resource:
            - Fn::GetAtt: CloudFormationServiceRole.Arn
      Tags:
      - Key: client
        Value:
          Ref: ClientShortName
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service: codebuild.amazonaws.com
      Tage:
      - Key: Name
        Value: CodeBuildRole
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: CloudWatchLogsPolicy
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Sid: S3AccessPolicy
            Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: '*'
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: CloudFormationServiceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Tags:
      - Key: Name
        Value:
          Ref: ClientShortName
      Policies:
      - PolicyName: CloudFormationServicePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Resource: '*'
            Action:
            - '*'
