service: s3-with-lambda
frameworkVersion: '3'

custom:
    bucket: aws-test-laravel-16

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: "dev"
  region: "us-east-1"
  iamRoleStatements:  # lambda function permission on S3 Bucket
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"

functions:
  PushCommit:
    handler: git-api.pushCommit
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          existing: true 
          forceDeploy: true

resources:
  Resources:
    s3WithLambda:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
