version: 0.0
os: linux
files:
- source: /index.php
  destination: /var/www/html/index.php
hooks:
  AfterInstall:
  - location: pre-install.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: start_server.sh
    timeout: 300
    runas: root
  ApplicationStop:
  # - location: stop_server.sh
  - location: post-install.sh
    timeout: 300
    runas: root


    # change file