version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.x
      nodejs: 16.x

    commands:
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/bin/composer
      - npm i aws-sdk
      - npm i -g serverless
  pre_build:
    commands:
      - cd admin
      # - serverless plugin install -n serverless-lift
      # - composer install --optimize-autoloader --no-dev
  build:
    commands:
      - 

  post_build:
    commands:
      # - cd ../ci-cd
      - bash exportData.sh
      - bash importData.sh
      - aws codebuild update-project  --name cp-cb-test --environment type="LINUX_CONTAINER",image="image",computeType="BUILD_GENERAL1_SMALL",environmentVariables=["{"name"="test","value"="test","type"="PLAINTEXT"}"]

artifacts:
  files:
    - '**/*'
