AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation template for this Serverless application
Resources:
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/app1-dev-api
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
          Fn::Join:
          - '-'
          - - app1
            - dev
            - lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/app1-dev*:*
          - Effect: Allow
            Action:
            - logs:PutLogEvents
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/app1-dev*:*:*
          - Effect: Allow
            Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - sqs:SendMessage
            Resource:
            - arn:aws:sqs:us-east-1:858183837623:researchJob
            - arn:aws:dynamodb:us-east-1:*:*
      Path: /
      RoleName:
        Fn::Join:
        - '-'
        - - app1
          - dev
          - Ref: AWS::Region
          - lambdaRole
  ApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: public/index.php
      Runtime: provided.al2
      FunctionName: app1-dev-api
      MemorySize: 1024
      Timeout: 28
      Role:
        Fn::GetAtt:
        - IamRoleLambdaExecution
        - Arn
      Layers:
      - arn:aws:lambda:us-east-1:209497400698:layer:php-81-fpm:32
      Code:
        S3Bucket: apnnew
        S3Key: ac35ae1f4e207e752b7d984f434c77bc
    DependsOn:
    - ApiLogGroup
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: dev-app1
      ProtocolType: HTTP
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: HttpApi
      StageName: $default
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: false
  ApiLambdaPermissionHttpApi:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - ApiLambdaFunction
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ':execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: HttpApi
          - /*
  HttpApiIntegrationApi:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
        - ApiLambdaFunction
        - Arn
      PayloadFormatVersion: '2.0'
  HttpApiRouteDefault:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: HttpApi
      RouteKey: $default
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: HttpApiIntegrationApi
    DependsOn: HttpApiIntegrationApi
  websiteAssets2A73BB69:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  websiteAssetsPolicyFDAAA9C0:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: websiteAssets2A73BB69
      PolicyDocument:
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - websiteCDNOrigin2S3OriginED10E993
              - S3CanonicalUserId
          Resource:
            Fn::Join:
            - ''
            - - Fn::GetAtt:
                - websiteAssets2A73BB69
                - Arn
              - /*
        - Action: s3:GetObject
          Effect: Allow
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - websiteCDNOrigin3S3OriginCE7BBD15
              - S3CanonicalUserId
          Resource:
            Fn::Join:
            - ''
            - - Fn::GetAtt:
                - websiteAssets2A73BB69
                - Arn
              - /*
        - Action: s3:GetObject
          Effect: Allow
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - websiteCDNOrigin4S3Origin12CC29FE
              - S3CanonicalUserId
          Resource:
            Fn::Join:
            - ''
            - - Fn::GetAtt:
                - websiteAssets2A73BB69
                - Arn
              - /*
        - Action: s3:GetObject
          Effect: Allow
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - websiteCDNOrigin5S3Origin34B95032
              - S3CanonicalUserId
          Resource:
            Fn::Join:
            - ''
            - - Fn::GetAtt:
                - websiteAssets2A73BB69
                - Arn
              - /*
        Version: '2012-10-17'
  websiteBackendOriginPolicy1F13AB4E:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Comment: Origin request policy for the website website.
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
          - Accept
          - Accept-Language
          - Content-Type
          - Origin
          - Referer
          - User-Agent
          - X-Requested-With
          - X-Forwarded-Host
        Name: app1-dev-website
        QueryStringsConfig:
          QueryStringBehavior: all
  websiteBackendCachePolicyE2870E5E:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Cache policy for the website website.
        DefaultTTL: 0
        MaxTTL: 31536000
        MinTTL: 0
        Name: app1-dev-website
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: all
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
            - Authorization
          QueryStringsConfig:
            QueryStringBehavior: all
  websiteRequestFunction9E9EBB7A:
    Type: AWS::CloudFront::Function
    Properties:
      Name: app1-dev-us-east-1-website-request
      AutoPublish: true
      FunctionCode: "function handler(event) {\n    var request = event.request;\n\
        \    request.headers[\"x-forwarded-host\"] = request.headers[\"host\"];\n\
        \    return request;\n}"
      FunctionConfig:
        Comment: app1-dev-us-east-1-website-request
        Runtime: cloudfront-js-1.0
  websiteCDNOrigin2S3OriginED10E993:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for websiteCDNOrigin2BA1CC1CD
  websiteCDNOrigin3S3OriginCE7BBD15:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for websiteCDNOrigin36B7E5D97
  websiteCDNOrigin4S3Origin12CC29FE:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for websiteCDNOrigin4F20241D3
  websiteCDNOrigin5S3Origin34B95032:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for websiteCDNOrigin5A04B149B
  websiteCDN060D946D:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
        - AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          PathPattern: /js/*
          TargetOriginId: websiteCDNOrigin2BA1CC1CD
          ViewerProtocolPolicy: redirect-to-https
        - AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          PathPattern: /css/*
          TargetOriginId: websiteCDNOrigin36B7E5D97
          ViewerProtocolPolicy: redirect-to-https
        - AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          PathPattern: /images/*
          TargetOriginId: websiteCDNOrigin4F20241D3
          ViewerProtocolPolicy: redirect-to-https
        - AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          PathPattern: /theme/*
          TargetOriginId: websiteCDNOrigin5A04B149B
          ViewerProtocolPolicy: redirect-to-https
        Comment: app1-dev website website CDN
        CustomErrorResponses:
        - ErrorCachingMinTTL: 0
          ErrorCode: 500
        - ErrorCachingMinTTL: 0
          ErrorCode: 504
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - PATCH
          - POST
          - DELETE
          CachePolicyId:
            Ref: websiteBackendCachePolicyE2870E5E
          Compress: true
          FunctionAssociations:
          - EventType: viewer-request
            FunctionARN:
              Fn::GetAtt:
              - websiteRequestFunction9E9EBB7A
              - FunctionARN
          OriginRequestPolicyId:
            Ref: websiteBackendOriginPolicy1F13AB4E
          TargetOriginId: websiteCDNOrigin173C249FC
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
        - CustomOriginConfig:
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
            - TLSv1.2
          DomainName:
            Fn::Join:
            - .
            - - Ref: HttpApi
              - execute-api.us-east-1.amazonaws.com
          Id: websiteCDNOrigin173C249FC
        - DomainName:
            Fn::GetAtt:
            - websiteAssets2A73BB69
            - RegionalDomainName
          Id: websiteCDNOrigin2BA1CC1CD
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ''
              - - origin-access-identity/cloudfront/
                - Ref: websiteCDNOrigin2S3OriginED10E993
        - DomainName:
            Fn::GetAtt:
            - websiteAssets2A73BB69
            - RegionalDomainName
          Id: websiteCDNOrigin36B7E5D97
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ''
              - - origin-access-identity/cloudfront/
                - Ref: websiteCDNOrigin3S3OriginCE7BBD15
        - DomainName:
            Fn::GetAtt:
            - websiteAssets2A73BB69
            - RegionalDomainName
          Id: websiteCDNOrigin4F20241D3
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ''
              - - origin-access-identity/cloudfront/
                - Ref: websiteCDNOrigin4S3Origin12CC29FE
        - DomainName:
            Fn::GetAtt:
            - websiteAssets2A73BB69
            - RegionalDomainName
          Id: websiteCDNOrigin5A04B149B
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ''
              - - origin-access-identity/cloudfront/
                - Ref: websiteCDNOrigin5S3Origin34B95032
