version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    
    commands:
        - ls
  pre_build:
    commands:
      
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p Test
      - cd Test
      - echo create test folder............
      - ls
      # - git clone https://vijayamin:glpat-nmPsiuU3wndrXU4XUeq7@gitlab.com/zepter-cloud/roomzz-web.git
      - git clone https://Urvesh05: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@github.com/Urvesh05/github-aws-cicd.git
      - ls
      - cd roomzz-web
      - ls
      - echo clone success..............
      # - git pull
      # - echo git pull success.......
      - git checkout test-cicd
      - ls
      - echo branch checkout success............
      # - aws s3 cp s3://git-hub-cicd-test-demo-123/APP/common.json src/contants/
      # - node --version
      # - npm install
      # - npm run build
      # - aws s3 cp build s3://git-hub-cicd-test-demo-123 --recursive
      # - echo copy build success..........
      ## - cd deploy-backend
      ## - bash deploy.sh  ## cloudFront

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
     - '**/*'